### ISSUE TITLE
Authentication failed for registration

### ISSUE THREAD

**Issue by keidischoi** [WaresWichall/hass-anycubic_cloud#37]
I registered with home assistant, but it doesn't work as shown in the image. I tried using the Slicer method, but there is no token in the path setting file.
![스크린샷 2024-11-07 221139](https://github.com/user-attachments/assets/8e318e57-733c-4053-9adc-2d4ba3602616)

**Comment by WaresWichall** [comment]
@keidischoi are you using the pre-release `v0.2.1rc3` ?

Have you logged in with the slicer? Which version of the slicer are you using?

Can you please translate the text in that image for me?
Thanks

**Comment by WaresWichall** [comment]
@keidischoi sorry I think this is actually an issue with the model of printer you have, which is untested. Which printer do you have?

**Comment by WaresWichall** [comment]
I think I've fixed this bug @keidischoi 

Try this release: [v0.2.1rc4](https://github.com/WaresWichall/hass-anycubic_cloud/releases/tag/v0.2.1rc4)

Let me know about my above slicer questions so we can get that working for you too.

**Comment by keidischoi** [comment]
Sorry for the late reply. It works fine after upgrading to v0.2.1rc4. My model is M7 Pro. Thank you.

**Comment by WaresWichall** [comment]
Great thanks for letting me know :) did you manage to find your slicer token too?

**Comment by keidischoi** [comment]
I still can't find anything about slicer tokens, but that's fine with me since I don't use them.
tanks you.

%AppData%\AnycubicSlicerNext\AnycubicSlicerNext.conf
{
    "anycubic_presets": [
        {
            "curr_bed_type": "3",
            "filament": "Anycubic PLA @Anycubic Kobra 2 0.4 nozzle",
            "filament_colors": "#69A4FF",
            "flush_volumes_matrix": "0.000000",
            "flush_volumes_vector": "140.000000|140.000000",
            "machine": "Anycubic Kobra 2 0.4 nozzle",
            "process": "0.20mm Standard @Anycubic Kobra 2 0.4 nozzle"
        },
        {
            "curr_bed_type": "3",
            "filament": "Default Filament",
            "filament_colors": "#69A4FF",
            "flush_volumes_matrix": "0.000000",
            "flush_volumes_vector": "140.000000|140.000000",
            "machine": "Default Printer",
            "process": "Default Setting"
        }
    ],
    "app": {
        "allow_ip_resolve": true,
        "anycubic_china_tag": false,
        "anycubic_test_env": false,
        "associate_3mf": false,
        "associate_step": false,
        "associate_stl": false,
        "auto_calculate": true,
        "auto_calculate_when_filament_change": true,
        "backup_interval": "10",
        "backup_switch": true,
        "camera_navigation_style": "0",
        "check_stable_update_only": false,
        "curr_bed_type": "3",
        "dark_color_mode": "0",
        "default_page": "1",
        "developer_mode": false,
        "download_path": "C:\\Users\\keidis\\Downloads",
        "drop_project_action": true,
        "enable_multi_machine": false,
        "enable_ssl_for_ftp": true,
        "enable_ssl_for_mqtt": true,
        "flush_multiplier": "1.000000",
        "internal_developer_mode": false,
        "iot_environment": "3",
        "keyboard_supported": "none/alt/control/shift",
        "language": "en_GB",
        "last_backup_path": "C:\\Users\\keidis\\AppData\\Local\\Temp/anycubicslicer_model/Thu_Sep_26/14_43_58#49520#34",
        "log_severity_level": "warning",
        "max_recent_count": "18",
        "max_send": "3",
        "mouse_supported": "mouse left/mouse middle/mouse right",
        "mouse_wheel": "0",
        "move_view": "none/mouse left",
        "pc_device_id": "3E7CE1062716EE8F72AA0A58F14CB46E",
        "precise_control": "none/mouse left",
        "preset_folder": "",
        "privacy_version": "00.00.00.00",
        "region": "Global",
        "remember_printer_config": true,
        "reverse_mouse_wheel_zoom": false,
        "rotate_view": "none/mouse left",
        "sending_interval": "5",
        "show_3d_navigator": true,
        "show_build_edgets": false,
        "show_daily_tips": true,
        "show_gcode_window": true,
        "show_hints": false,
        "show_home_page": true,
        "show_model_mesh": false,
        "show_model_shadow": true,
        "show_printable_box": true,
        "show_splash_screen": false,
        "single_instance": false,
        "slicer_uuid": "552fa25d-e466-4db2-b5be-71ecdc7561b1",
        "stealth_mode": false,
        "sync_system_preset": true,
        "sync_user_preset": false,
        "sys_menu_enabled": "1",
        "toolkit_size": "83",
        "units": "0",
        "use_free_camera": false,
        "use_inches": "0",
        "use_legacy_3DConnexion": true,
        "use_perspective_camera": true,
        "user_mode": "simple",
        "version": "1.1.1.0",
        "window_layout": "layout2|name=sidebar;caption=;state=1996;dir=4;layer=0;row=0;pos=0;prop=100000;bestw=420;besth=900;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|name=main;caption=;state=256;dir=5;layer=0;row=0;pos=0;prop=100000;bestw=20;besth=20;minw=-1;minh=-1;maxw=-1;maxh=-1;floatx=-1;floaty=-1;floatw=-1;floath=-1|dock_size(5,0,0)=20|dock_size(4,0,0)=422|",
        "window_mainframe": "1120; 320; 1200; 800; 0",
        "zoom_to_mouse": false,
        "zoom_view": "none/mouse left"
    },
    "filaments": [
        "Anycubic ASA @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PETG @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 2 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 2 Max 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 2 Neo 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 2 Plus 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 2 Pro 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 3 0.2 nozzle",
        "Anycubic PLA @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PLA @Anycubic Kobra 3 0.6 nozzle",
        "Anycubic PLA @Anycubic Kobra 3 0.8 nozzle",
        "Anycubic PLA Glow @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PLA High Speed @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PLA Matte @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PLA SE @Anycubic Kobra 3 0.4 nozzle",
        "Anycubic PLA Slik @Anycubic Kobra 3 0.4 nozzle",
        "Generic ABS @Anycubic Kobra 3 0.4 nozzle",
        "Generic TPU @Anycubic Kobra 3 0.4 nozzle"
    ],
    "firstguide": {
        "finish": true,
        "privacyuse": false
    },
    "header": "AnycubicSlicerNext 1.1.1",
    "models": [
        {
            "model": "Anycubic Kobra 2",
            "nozzle_diameter": "0.4",
            "vendor": "Anycubic"
        },
        {
            "model": "Anycubic Kobra 2 Max",
            "nozzle_diameter": "0.4",
            "vendor": "Anycubic"
        },
        {
            "model": "Anycubic Kobra 2 Neo",
            "nozzle_diameter": "0.4",
            "vendor": "Anycubic"
        },
        {
            "model": "Anycubic Kobra 2 Plus",
            "nozzle_diameter": "0.4",
            "vendor": "Anycubic"
        },
        {
            "model": "Anycubic Kobra 2 Pro",
            "nozzle_diameter": "0.4",
            "vendor": "Anycubic"
        },
        {
            "model": "Anycubic Kobra 3",
            "nozzle_diameter": "0.4",
            "vendor": "Anycubic"
        }
    ],
    "presets": {
        "filaments": null,
        "machine": "Anycubic Kobra 2 0.4 nozzle"
    },
    "print": {
        "bed_leveling": "1",
        "flow_cali": "1",
        "timelapse": "1"
    }
}
# MD5 checksum EF4EA335DC9BF582ADE508162DD788CD
